### ISSUE TITLE
Github Action 发布 npm 包

### ISSUE THREAD

**Issue by hughfenghen** [hughfenghen/hughfenghen.github.io#48]
最近开发[Erra](https://github.com/hughfenghen/erra)项目，发布npm包整个过程大概需要5分钟。  
尝试使用Github Action来实现自动发布。  

[最终结果如下](https://github.com/hughfenghen/erra/actions?query=workflow%3Anpm-publish)：  
```yaml
name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.13.0
    - name: NPM or Yarn install with caching
      uses: bahmutov/npm-install@v1.1.0
    - name: Publish to npm
      uses: pascalgn/npm-publish-action@1.1.0
      with: # All of theses inputs are optional
        tag_name: "v%s"
        tag_message: "v%s"
        commit_pattern: "^\\s*v((\\d+\\.){2}\\d+)\\s*$"
      env: # More info about the environment variables in the README
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
```

触发构建（`yarn publish`）的条件：  
git push  
&& package.json中的version值改变  
&& 有commit message能被`commit_pattern: "^\\s*v((\\d+\\.){2}\\d+)\\s*$"`匹配上  
&& 正则匹配的**[第一个分组](https://github.com/pascalgn/npm-publish-action/blob/master/index.js#L79)**（不了解请搜索：正则捕获分组）与version相同

详情参考：  
[pascalgn/npm-publish-action](https://github.com/pascalgn/npm-publish-action)  

------

NPM_AUTH_TOKEN在[这里](https://www.npmjs.com/settings/hughfenghen/tokens)创建。  
![image](https://user-images.githubusercontent.com/3307051/70863291-7a38b380-1f81-11ea-935f-95472269055f.png)
  
然后粘贴到github项目的`setting > Secrets`中，注释命名需要保持一致。    
![image](https://user-images.githubusercontent.com/3307051/70863219-a0118880-1f80-11ea-9ee9-4fbcd6de86f3.png)
