### ISSUE TITLE
Github Action 自动发布项目到 Github Pages

### ISSUE THREAD

**Issue by hughfenghen** [hughfenghen/hughfenghen.github.io#50]
*篇首语：Github Actions能让你自由组合多个功能节点，搭建自己的工作流。你可以在[这里](https://github.com/marketplace?type=actions)搜索关键字，查看别人贡献的Action，也可以自己参考文档自己实现一些特殊逻辑。*

参考：https://github.com/hughfenghen/webrtc-nsc/blob/master/.github/workflows/deploy-gh-pages.yml

```yml
name: GitHub Pages deploy
on:
  push:
    branches:
      - master
jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout  # Checkout项目
      uses: actions/checkout@master
    - name: Set up Node.js  # Nodejs版本
      uses: actions/setup-node@master
      with:
        node-version: 12.13.0
    - name: NPM or Yarn install with caching # install
      uses: bahmutov/npm-install@v1.1.0
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: build # run `yarn build` command
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@2.0.0
      env:
        EMAIL: arnaud@ligny.org               # 你的Github邮箱
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 看下文描述
        BUILD_DIR: dist/                     # deploy到Github Pages的目录，默认"_site/" 
```
1. 执行的步骤看注释，应该算非常清晰了。  
2. 单个步骤（step）的仓库地址是去掉uses中的版本信息，以`Checkout`为例，仓库地址：https://github.com/actions/checkout。可以查看文档和实现细节。
3. 生成`secrets.ACCESS_TOKEN`，首先生成一个[token](https://github.com/settings/tokens)，然后将token配置到当前仓库的setting中。
![image](https://user-images.githubusercontent.com/3307051/72677936-616d7180-3adc-11ea-85ae-2fd5da2d0ad8.png)
